# -- Global Configuration for labels, etc.
global: {}
#  labels:
#    part-of: "gateway-api"

# -- Gateway Class Configuration
gatewayClass:
  enabled: true
  # -- Controller reference
  controllerName: "gateway.envoyproxy.io/gatewayclass-controller"

# -- Gateway API Configuration
gateway:
  enabled: true
  # -- Define listeners in any format according an original Gateway API spec
  listeners:
    - name: prod-web
      protocol: HTTP
      port: 80
#    - name: prod-web-https
#      hostname: mydomain.com
#      port: 443
#      protocol: HTTPS
#      tls:
#        mode: Terminate
#        certificateRefs:
#        - name: mydomain-com-tls
#          kind: Secret
