{{- if .Values.crds.enabled }}
{{- $crdsPath := printf "crds/%s" .Values.crds.mode -}}
{{- range $path, $_ := .Files.Glob (printf "%s/*.yaml" $crdsPath) }}
  {{- $crd := $.Files.Get $path | fromYaml }}
  {{- if not (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" $crd.metadata.name) }}
---
{{ $.Files.Get $path }}
  {{- end }}
{{- end }}
{{- end }}
